# Refresh Browser Database Action
#
# Ensure latest browser and browser polyfills represent current usage
#
# Context: https://github.com/browserslist/update-db
name: Refresh Browser DB

on:
  schedule:
    - cron: '28 05 * * 6'
  workflow_dispatch:

permissions:
  contents: read

jobs:
    refresh:
        name: prepare-repo
        runs-on: ubuntu-latest

        permissions:
          actions: write
          contents: write
          pull-requests: write

        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
            with:
              egress-policy: audit

          - name: Checkout Repo
            uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            with:
              show-progress: false

          - name: Install pnpm
            uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
            id: pnpm-install
            with:
              run_install: false

          - name: Install Node.js
            uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
            with:
              node-version: 20
              cache: 'pnpm'

          - name: Get Store Directory
            id: pnpm-cache
            shell: bash
            run: |
              echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

          - name: Setup Cache
            uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
            with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                ${{ runner.os }}-pnpm-store-

          - name: Install Dependencies
            run: pnpm install

          - name: Refresh DB
            run: pnpx update-browserslist-db@latest

          - id: refreshed
            run: echo "refreshed=$(git diff --name-only --exit-code HEAD pnpm-lock.yaml)" >> $GITHUB_OUTPUT

          - name: Create Pull Request
            if: ${{ steps.refreshed.outputs.refreshed != '' }}
            env:
              GH_TOKEN: ${{ github.token }}
            run: |
              git config --global user.name "github-actions"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git checkout -b refresh-caniuse
              git add pnpm-lock.yaml
              git commit -s -m "chore(deps): refresh caniuse browser database"
              git push origin refresh-caniuse
              gh pr create --title "chore(deps): refresh caniuse browser database" --body "Automagically created"
