# Refresh Browser Database Action
#
# Ensure latest browser and browser polyfills represent current usage
#
# Context: https://github.com/browserslist/update-db
name: Refresh Browser DB

on:
  schedule:
    - cron: '28 05 * * 6'
  workflow_dispatch:

permissions: {}

jobs:
    refresh:
        name: prepare-repo
        runs-on: ubuntu-latest

        permissions:
          actions: write
          contents: write
          pull-requests: write

        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
            with:
              disable-sudo: true
              egress-policy: block
              allowed-endpoints: >
                api.github.com:443
                github.com:443
                nodejs.org:443
                objects.githubusercontent.com:443
                raw.githubusercontent.com:443
                registry.npmjs.org:443
                unpkg.com:443

          - name: Checkout Repo
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              persist-credentials: false
              show-progress: false

          - name: Install pnpm
            uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
            id: pnpm-install
            with:
              run_install: false

          - name: Install Node.js
            uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
            with:
              node-version: 20
              cache: 'pnpm'

          - name: Get Store Directory
            id: pnpm-cache
            shell: bash
            run: |
              echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

          - name: Setup Cache
            uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
            with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                ${{ runner.os }}-pnpm-store-

          - name: Install Dependencies
            run: pnpm install

          - name: Refresh DB
            run: pnpx update-browserslist-db@latest

          - id: refreshed
            run: echo "refreshed=$(git diff --name-only --exit-code HEAD pnpm-lock.yaml)" >> $GITHUB_OUTPUT

          - name: Create Pull Request
            if: ${{ steps.refreshed.outputs.refreshed != '' }}
            env:
              GH_TOKEN: ${{ github.token }}
            run: |
              git config --global user.name "github-actions"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git checkout -b refresh-caniuse
              git add pnpm-lock.yaml
              git commit -s -m "chore(deps): refresh caniuse browser database"
              git push origin refresh-caniuse
              gh pr create --title "chore(deps): refresh caniuse browser database" --body "Automagically created"
